export * from 'components/App/App';
export * from 'components/Section/Section.styled.js';
export * from 'components/Container/Container.styled.js';
export * from 'components/Heading/Heading.styled.js';
export * from 'components/Profile/Profile';
export * from 'components/FriendList/FriendList.js';
export * from 'components/FriendListItem/FriendListItem.js';
export * from 'components/Statistics/Statistics.js';
export * from 'components/StatisticItem/StatisticItem.js';
// export * from 'components/CryptoHistory/CryptoHistory.js';
